version: '3.8'

services:
  auto_parser:
    build: .
    container_name: auto_parser
    volumes:
      - ./excel_storage:/app/excel_storage
    environment:
      - CHROME_BIN=/usr/bin/chromium
      - CHROMEDRIVER_PATH=/usr/bin/chromedriver
    restart: unless-stopped